// Generated by scripts/optimize-assets.mjs — do not edit by hand.
export const storyBlurDataURL =
  "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwAwCdASoUAA0APwlur0+rpiQiMAgBcCEJZV/2ADc1ZmaAAP7wBQK+/ALzudx4Od/tIZyvcgt/UK5f4mZOKwIA";
