/**
 * One-off asset pipeline.
 *
 * Converts the source story artwork into a responsive WebP set and rasterises
 * the brand mark into the PNG sizes that iOS/Android home screens require.
 * Re-run with `node scripts/optimize-assets.mjs` if the source art changes.
 */
import sharp from "sharp";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const out = path.join(root, "public");
const source = process.argv[2] ?? "/tmp/story.png";

await mkdir(path.join(out, "img"), { recursive: true });

// Responsive WebP variants for the story visual.
for (const width of [800, 1200, 1600]) {
  const file = path.join(out, "img", `story-bridge-${width}.webp`);
  await sharp(source).resize({ width }).webp({ quality: 76, effort: 6 }).toFile(file);
  console.log("wrote", path.relative(root, file));
}

// Tiny inline placeholder so the image fades in over its own colours.
const lqip = await sharp(source).resize({ width: 20 }).webp({ quality: 32 }).toBuffer();
await writeFile(
  path.join(root, "src", "content", "story-blur.ts"),
  `// Generated by scripts/optimize-assets.mjs — do not edit by hand.\n` +
    `export const storyBlurDataURL =\n  "data:image/webp;base64,${lqip.toString("base64")}";\n`,
);
console.log("wrote src/content/story-blur.ts");

// Rasterise the brand mark for platforms that will not take SVG.
const markSvg = await readFile(path.join(root, "src", "app", "icon.svg"));
for (const [size, name] of [
  [180, "apple-icon.png"],
  [512, "icon-512.png"],
  [192, "icon-192.png"],
]) {
  const file = path.join(out, name);
  await sharp(markSvg, { density: 400 }).resize(size, size).png().toFile(file);
  console.log("wrote", path.relative(root, file));
}
